sudo: false
dist: trusty
language: c++
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
install:
 - ./.ci/travis-prepare.sh
script:
 - ./.ci/travis-build.sh
env:
 - BRCORE=master BRLIBCOM=master BRPVD=master BRPVA=master BRNT=master TEST=NO
 - CMPLR=clang TEST=NO
 - EXTRA="CMD_CXXFLAGS=-std=c++11" TEST=NO
 - CMPLR=clang EXTRA="CMD_CXXFLAGS=-std=c++11" TEST=NO
 - WINE=32 TEST=NO STATIC=YES TEST=NO
 - WINE=32 TEST=NO STATIC=NO TEST=NO
 - RTEMS=4.10 TEST=NO
 - RTEMS=4.9 TEST=NO
 - BRBASE=3.16 TEST=NO
 - BRBASE=3.15 TEST=NO
 - BRBASE=3.14 TEST=NO
